### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [Shipra0011/projects#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

https://splurty-hi.herokuapp.com/

**Comment by Shipra0011** [comment]
Dear Michael, 

I added `<meta name="viewport" content="width=device-width, initial-scale=1">`
under the head tag in the application.html.erb file.

How it looks: https://splurty-hi.herokuapp.com/

**Comment by Mikeysax** [comment]
Nice job, Thumbs up!
